import type { Metadata } from "next";
import { Noto_Serif, Manrope } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import ReduxProvider from "@/redux-provider";
import Navbar from "@/components/Navbar";
import AuthContextWrapper from "@/context/AuthContextWrapper";
import { ToastContainer } from "react-toastify";

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
});

const manRope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${notoSerif.variable} ${manRope.variable} h-full antialiased}`}
    >
      <body className="min-h-full flex flex-col">
        <ToastContainer/>
        <ReduxProvider>
          <AuthContextWrapper>
            <Navbar />
            {children}
            <Footer />
          </AuthContextWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
};
